In [1]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

In [2]:

arr = np.array([1, 2, 3, 6, 4, 5])
print("Reversed:", arr[::-1])

Reversed: [5 4 6 3 2 1]


In [3]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Flatten (method 1):", array1.flatten())
print("Flatten (method 2):", array1.ravel())

Flatten (method 1): [1 2 3 2 4 5 1 2 3]
Flatten (method 2): [1 2 3 2 4 5 1 2 3]


In [5]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print("Arrays equal:", np.array_equal(arr1, arr2))



Arrays equal: True


In [6]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
for arr in [x, y]:
    vals, counts = np.unique(arr, return_counts=True)
    max_val = vals[np.argmax(counts)]
    indices = np.where(arr == max_val)[0]
    print(f"Most frequent: {max_val}, Indices: {indices}")

Most frequent: 1, Indices: [0 5 7 8 9]
Most frequent: 1, Indices: [0 1 2]


In [7]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Total Sum:", gfg.sum())
print("Row-wise Sum:", np.sum(gfg, axis=1))
print("Column-wise Sum:", np.sum(gfg, axis=0))


Total Sum: 45
Row-wise Sum: [[14]
 [16]
 [15]]
Column-wise Sum: [[20  9 16]]


In [8]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
print("Diagonal sum:", np.trace(n_array))
eig_vals, eig_vecs = np.linalg.eig(n_array)
print("Eigenvalues:", eig_vals)
print("Eigenvectors:\n", eig_vecs)
print("Inverse:\n", np.linalg.inv(n_array))
print("Determinant:", np.linalg.det(n_array))


Diagonal sum: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [10]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
print("Mult 1:\n", np.dot(p1, q1))
print("Covariance 1:\n", np.cov(p1.T, q1.T))

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
print("Mult 2:\n", np.dot(p2, q2))
print("Covariance of p2:\n", np.cov(p2.T))
print("Covariance of q2:\n", np.cov(q2.T))

Mult 1:
 [[16 19]
 [26 31]]
Covariance 1:
 [[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]
Mult 2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance of p2:
 [[2.33333333 2.33333333]
 [2.33333333 2.33333333]]
Covariance of q2:
 [[2.  2.  1. ]
 [2.  2.  1. ]
 [1.  1.  0.5]]


In [11]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("Inner product:", np.inner(x, y))
print("Outer product:\n", np.outer(x, y))
print("Cartesian product:\n", np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2))


Inner product: [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [12]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
flat = array.flatten()
print("Absolute:\n", np.abs(array))
print("Percentiles (Flat):", np.percentile(flat, [25, 50, 75]))
print("Percentiles (Cols):", np.percentile(array, [25, 50, 75], axis=0))
print("Percentiles (Rows):", np.percentile(array, [25, 50, 75], axis=1))
print("Mean:", np.mean(flat), "Median:", np.median(flat), "Std:", np.std(flat))
print("Mean (Rows):", np.mean(array, axis=1))
print("Mean (Cols):", np.mean(array, axis=0))

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Floor:", np.floor(a))
print("Ceil:", np.ceil(a))
print("Trunc:", np.trunc(a))
print("Round:", np.round(a))


Absolute:
 [[1 2 3]
 [4 5 6]]
Percentiles (Flat): [-3.5 -0.5  2.5]
Percentiles (Cols): [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles (Rows): [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean: -0.5 Median: -0.5 Std: 3.8622100754188224
Mean (Rows): [ 0.66666667 -1.66666667]
Mean (Cols): [-1.5  1.5 -1.5]
Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Trunc: [-1. -1. -0.  0.  1.  1.  3.]
Round: [-2. -2. -0.  0.  2.  2.  3.]


In [13]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted:", np.sort(array))
print("Sorted Indices:", np.argsort(array))
print("4 smallest:", np.partition(array, 3)[:4])
print("5 largest:", np.sort(array)[-5:])

array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
ints = array[array == array.astype(int)]
floats = array[array != array.astype(int)]
print("Integers:", ints)
print("Floats:", floats)

Sorted: [ 10  16  16  52  54  62 453]
Sorted Indices: [0 3 4 1 5 2 6]
4 smallest: [10 16 16 52]
5 largest: [ 16  52  54  62 453]
Integers: [1. 2. 3. 2.]
Floats: [1.2 2.2]


In [14]:
def img_to_array(path):
    img = Image.open(path)
    img_array = np.array(img)
    if len(img_array.shape) == 2:
        np.savetxt("gray_image.txt", img_array, fmt='%d')
        print("Saved grayscale image array to gray_image.txt")
    else:
        np.savetxt("rgb_image.txt", img_array.reshape(-1, img_array.shape[-1]), fmt='%d')
        print("Saved RGB image array to rgb_image.txt")

def load_saved_file(path):
    data = np.loadtxt(path, dtype=int)
    print("Loaded data:\n", data)